### ISSUE TITLE
On 5.0.5 I get this error : Cannot read property 'indicators' of undefined

### ISSUE THREAD

**Issue by oefterdal** [GuntharDeNiro/Gunthy#1]
stderr: pkg/prelude/bootstrap.js:1102
      throw error;
      ^

TypeError: Cannot read property 'indicators' of undefined
    at Object.<anonymous> (/snapshot/gunbot-build/tulind/index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1083:31)
    at require (internal/module.js:11:18)
    at __dirname (/snapshot/gunbot-build/bb.js:0:0)
    at Object.<anonymous> (/snapshot/gunbot-build/bb.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1083:31)
    at require (internal/module.js:11:18)
    at module.exports (/snapshot/gunbot-build/requirefix.js:0:0)
    at Timeout._.forEach._.forEach.Promise.then.setTimeout [as _onTimeout] (/snapshot/gunbot-build/bot.js:0:0)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)

**Comment by GuntharDeNiro** [comment]
@oefterdal you need the tulind folder: it is provided in the zip file

**Comment by oefterdal** [comment]
@GuntharDeNiro Sorry, thank you.
