### ISSUE TITLE
Can't trade EUR-BSV on Kraken

### ISSUE THREAD

**Issue by BestAir** [GuntharDeNiro/Gunthy#134]
When trying to trade EUR-BSV on Kraken, it results in error:

> Error: Query:Unknown asset pairnull
> {}
> Error: {}
>     at errorHandler (/snapshot/gblackv12/ctx/js/kraken.js:0:0)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by BestAir** [comment]
The same error for EUR-XTZ.

**Comment by BestAir** [comment]
Ha ha, they consider delisting BSV. Even so, the issue remains with XTZ.

**Comment by BestAir** [comment]
And ATOM.
