### ISSUE TITLE
5054 illegal operation on a directory

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/Gunthy#23]
Same config works in 5051, 5052 and 5053

```
[centos@ip-172-31-35-58 test]$ wget https://github.com/GuntharDeNiro/Gunthy/releases/download/5054/Gunthy_v5054_828fd3f_allOs.zip
...
[centos@ip-172-31-35-58 test]$ ./gunthy-linx64 
Loading config...
Bot crashed at 2017/10/04 14:55:36
Reason: Failed to load config!!!
Parameter: undefined
Original error: { Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:667:18)
    at Object.fs.readSync (pkg/prelude/bootstrap.js:502:32)
    at tryReadSync (fs.js:529:20)
    at Object.fs.readFileSync (fs.js:571:19)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:625:36)
    at Promise (/snapshot/gunbot-build/bot.lib.js:0:0)
    at Promise.module.exports.Promise._execute (/snapshot/gunbot-build/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise.module.exports.Promise._resolveFromExecutor (/snapshot/gunbot-build/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/snapshot/gunbot-build/node_modules/bluebird/js/release/promise.js:79:10)
    at t (/snapshot/gunbot-build/bot.lib.js:0:0)
    at Object.start (/snapshot/gunbot-build/bot.lib.js:0:0)
    at Object.<anonymous> (/snapshot/gunbot-build/bot.lib.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1083:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/gunbot-build/index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22) errno: -21, code: 'EISDIR', syscall: 'read' }
^C
```

**Comment by paramecie** [comment]
I had this too, suddenly one night.
If I remember well it was 5.0.4.
I guess they changed something on the server?
Anyway - try 5.0.5.5 RC, or back to 3.3.2...

**Comment by utdrmac** [comment]
@paramecie I was having issues with 5055 as well, which is why I attempted to roll back to 5054 but then this came up.  I resolved the 5055 issue which was with upstream proxy host.
