### ISSUE TITLE
Gunthy gui 7.0.2

### ISSUE THREAD

**Issue by Tonyrow** [GuntharDeNiro/Gunthy#66]
Getting error below causing restarting config, might happen 10 times per 1 minute. Any solutions?

        ^
TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^
TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by armanbcoin** [comment]
I got wrong pair, instead of USDT-BTC, I had but BTC-USDT for an example. and it would do that

**Comment by Dangerous-Mind** [comment]
If you don't have any coin from USDT you'll have that message also on all of the pairs on that instance.
